C     Diagram 1
      DATA MAPCONFIG(1)/1/
      DATA (IFOREST(I,-1,1),I=1,2)/4,3/
      DATA (SPROP(I,-1,1),I=1,1)/23/
      DATA TPRID(-1,1)/0/
      DATA (IFOREST(I,-2,1),I=1,2)/6,5/
      DATA (SPROP(I,-2,1),I=1,1)/101/
      DATA TPRID(-2,1)/0/
      DATA (IFOREST(I,-3,1),I=1,2)/1,-1/
      DATA TPRID(-3,1)/1/
      DATA (SPROP(I,-3,1),I=1,1)/0/
      DATA (IFOREST(I,-4,1),I=1,2)/-3,-2/
C     Diagram 2
      DATA MAPCONFIG(2)/2/
      DATA (IFOREST(I,-1,2),I=1,2)/6,5/
      DATA (SPROP(I,-1,2),I=1,1)/101/
      DATA TPRID(-1,2)/0/
      DATA (IFOREST(I,-2,2),I=1,2)/4,3/
      DATA (SPROP(I,-2,2),I=1,1)/23/
      DATA TPRID(-2,2)/0/
      DATA (IFOREST(I,-3,2),I=1,2)/1,-1/
      DATA TPRID(-3,2)/1/
      DATA (SPROP(I,-3,2),I=1,1)/0/
      DATA (IFOREST(I,-4,2),I=1,2)/-3,-2/
C     Number of configs
      DATA MAPCONFIG(0)/2/
