ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SiM_TSD_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_41 = ', GC_41
      WRITE(*,2) 'GC_42 = ', GC_42
      WRITE(*,2) 'GC_47 = ', GC_47
      WRITE(*,2) 'GC_48 = ', GC_48
      WRITE(*,2) 'GC_49 = ', GC_49
      WRITE(*,2) 'GC_50 = ', GC_50
      WRITE(*,2) 'GC_13 = ', GC_13
      WRITE(*,2) 'GC_21 = ', GC_21
