ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SiM_SVD_UFO_updated'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_20 = ', GC_20
      WRITE(*,2) 'GC_21 = ', GC_21
      WRITE(*,2) 'GC_23 = ', GC_23
      WRITE(*,2) 'GC_24 = ', GC_24
      WRITE(*,2) 'GC_29 = ', GC_29
      WRITE(*,2) 'GC_30 = ', GC_30
      WRITE(*,2) 'GC_31 = ', GC_31
      WRITE(*,2) 'GC_50 = ', GC_50
      WRITE(*,2) 'GC_51 = ', GC_51
      WRITE(*,2) 'GC_53 = ', GC_53
      WRITE(*,2) 'GC_54 = ', GC_54
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_12 = ', GC_12
      WRITE(*,2) 'GC_13 = ', GC_13
      WRITE(*,2) 'GC_14 = ', GC_14
      WRITE(*,2) 'GC_16 = ', GC_16
