ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MS,MDL_MXI,MDL_MU,MDL_MT,MDL_MW,MDL_MZ
     $ ,MDL_MTA,MDL_MC,MDL_MB,MDL_ME,MDL_MD,MDL_MH,MDL_MM,MDL_MCHI

      COMMON/MASSES/ MDL_MS,MDL_MXI,MDL_MU,MDL_MT,MDL_MW,MDL_MZ
     $ ,MDL_MTA,MDL_MC,MDL_MB,MDL_ME,MDL_MD,MDL_MH,MDL_MM,MDL_MCHI


      DOUBLE PRECISION MDL_WXI,MDL_WZ,MDL_WH,MDL_WW,MDL_WT

      COMMON/WIDTHS/ MDL_WXI,MDL_WZ,MDL_WH,MDL_WW,MDL_WT


      DOUBLE COMPLEX GC_20, GC_21, GC_23, GC_24, GC_29, GC_30, GC_31
     $ , GC_50, GC_51, GC_53, GC_54, GC_11, GC_12, GC_13, GC_14, GC_16

      COMMON/COUPLINGS/ GC_20, GC_21, GC_23, GC_24, GC_29, GC_30
     $ , GC_31, GC_50, GC_51, GC_53, GC_54, GC_11, GC_12, GC_13, GC_14
     $ , GC_16

